Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - schof.link
          - "*.schof.link"
          - mirri.link
          - "*.mirri.link"
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:672895027413:certificate/de552b7d-1f13-454a-8256-5f54b018ed1d
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: Bucket
          DefaultTTL: 31536000
          MinTTL: 31536000
          MaxTTL: 31536000
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
            Headers:
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
              - Origin
              - Authorization
          Compress: true
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: ApiGateway
            ViewerProtocolPolicy: redirect-to-https
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled policy
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # AllViewerExceptHostHeader policy
            ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd # CORS-With-Preflight policy
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
              Headers:
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
                - Origin
                - Authorization
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
        Enabled: true
        Origins:
          - Id: Bucket
            DomainName: schof-link-files.s3-website-eu-west-1.amazonaws.com
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
          - Id: ApiGateway
            DomainName: "#{HttpApi}.execute-api.eu-west-1.amazonaws.com"
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
