Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: schof-link-files
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
