service: schof-link

plugins:
  - serverless-esbuild
  - serverless-cloudfront-invalidate
  - serverless-cloudformation-sub-variables
  - serverless-offline

custom:
  cloudfrontInvalidate:
    - distributionId: EMJNEM0TGFXER
      items:
        - "/"
        - "/static/*"
        - "/assets/*"
        - "/fonts/*"
        - "/_markdown.css"
        - "/index.html"

provider:
  name: aws
  stage: production
  region: eu-west-1
  versionFunctions: false
  runtime: nodejs22.x
  stackTags:
    service: mirri
  environment:
    NODE_ENV: production
    SLACK_WEBHOOK: ${env:SLACK_WEBHOOK,''}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:HeadObject
            - s3:ListBucket
            - s3:ListBucketVersions
          Resource:
            - 'arn:aws:s3:::schof-link-files'
            - 'arn:aws:s3:::schof-link-files/*'
        - Effect: Allow
          Action:
            - cloudfront:CreateInvalidation
          Resource:
            - 'arn:aws:cloudfront::672895027413:distribution/EMJNEM0TGFXER'

package:
  individually: true

functions:
  - ${file(./src/functions/get-url/function.yml)}
  - ${file(./src/functions/md/function.yml)}
  - ${file(./src/functions/redirect/function.yml)}

resources:
  - ${file(./src/infrastructure/s3.yml)}
  - ${file(./src/infrastructure/cloudfront.yml)}
  - ${file(./src/infrastructure/dns.yml)}
